### ISSUE TITLE
Prepare for test release

### ISSUE THREAD

**Issue by tiadams** [SCAI-BIO/PDataViewer#17]
We should start with a test deployment to facilitate the actual release & make it possible for members of SCAI to test the current implemented features. We can update the test deployment based on releases we schedule after feature milestones that you define.

Steps would be:  

- [x] test containers (pdataviewer/frontend & pdataviewer/backend) @mehmetcanay 
- [x] #21
- [x] <del> create SCAI branch with adjusted URLs to backend (for now only internal: `pdata.k8s.scai.fraunhofer.de` & `api.pdata.k8s.scai.fraunhofer.de`) @mehmetcanay </del>
- [x] #20
- [x] #18
- [x] <del>setup protection rules for scai branch </del> 
- [x] #19
- [x] #25

Doing this ASAP can give us some feedback which may be useful for your thesis and possibly catch potential bugs before the actual release by the time of your submission.

**Comment by mehmetcanay** [comment]
> test containers (pdataviewer/frontend & pdataviewer/backend) @mehmetcanay

I think I already created the test containers in [docker-compose.local.yml](https://github.com/SCAI-BIO/PDataViewer/blob/main/docker-compose.local.yml).

**Comment by tiadams** [comment]
I am testing the docker-compose.yml right now. I renamed the image names to pdataviewer-frontend and pdataviewer-backend, I just noticed that this generic name might lead to collision issues with existing containers like it just did on my machine for syndat  :sweat_smile:  I will make a PR once the build is finished.

Regarding the second step, I found that in Angular we can just use build environments, please take a look at this:
https://stackoverflow.com/questions/47426721/angular-cli-change-rest-api-url-on-build

We should create a environment `dev` which builds the frontend with the localhost url as well as an environment `scai` which builds the frontend using the scai URL (will be something like the URL I mentioned above). I will create a seperate issue for this, please try to adapt this in your frontend code asap since you will be using the URL in most of your classes and it will be more work to implement this later on.
