### ISSUE TITLE
Add documentation on how to access containers started via docker-compose in README.md

### ISSUE THREAD

**Issue by tiadams** [SCAI-BIO/PDataViewer#21]
This is only minor; In the README.md it states that the frontend will be running on port 8080 when started locally, the docker-compose.local.yaml starts it on port 3000 - we should explicitly state this in the README so this does not have to be looked up in the docker-compsoe file itself

**Comment by mehmetcanay** [comment]
I addressed this issue in a new branch and I will create a pull request for it after the merging of frontend-dev branch to avoid breaking git again 😄

**Comment by tiadams** [comment]
Best practice would be:
Merge fix-readme into main > merge main into frontend > merge frontend into main

This way you should also avoid any conflicts
