### ISSUE TITLE
Requirement Analysis (Backend)

### ISSUE THREAD

**Issue by tiadams** [SCAI-BIO/PDataViewer#4]
- How many (and which) datasets will be included?
- What needs to be computed based on these datasets (e.g. summary statistics, models, plots)?

**Comment by mehmetcanay** [comment]
Datasets to be used:

- Parkinson's Progression Markers Initiative (PPMI)<sup>1</sup>
- The Fox Investigation for New Discovery of Biomarkers (BioFIND)<sup>1</sup>
- LRRK2 Cohort Consortium (LCC)<sup>1</sup>
- The Luxembourg Parkinson's Study (LuxPARK)<sup>2</sup>
- The Oxford Parkinson's Disease Center (OPDC)<sup>2</sup>
- Tracking Parkinson's Study (PRoBaND)<sup>2</sup>
- Fox Insight<sup>3</sup>

<sup>1</sup> Patient-level data is preprocessed, dictionary is mapped
<sup>2</sup> We do not have access to the patient-level data, but the dictionary is mapped
<sup>3</sup> We have access to the data but not yet been preprocessed or mapped.
