### ISSUE TITLE
Embedding Visualization

### ISSUE THREAD

**Issue by mehmetcanay** [SCAI-BIO/PDataViewer#41]
Implement the Parkinson's disease data

**Comment by tiadams** [comment]
Could also be mocked using the html from here:
https://github.com/SCAI-BIO/tsnepad/blob/main/index.html

**Comment by mehmetcanay** [comment]
The embedding visualization is implemented in [INDEX API](https://github.com/SCAI-BIO/index/blob/main/api/routes.py#L92), closing the issue.
