### ISSUE TITLE
Update version during release

### ISSUE THREAD

**Issue by mehmetcanay** [SCAI-BIO/PDataViewer#46]
Update the versions of API (in routes.py) and PDataViewer (in package-lock.json) automatically during release.

**Comment by mehmetcanay** [comment]
For Angular versioning I found this: https://medium.com/@tolvaly.zs/how-to-version-number-angular-6-applications-4436c03a3bd3

For API versioning I found a code snippet like this:
- name: Increment API Version
      id: increment_version
      run: |
        import re

        file_path = "backend/routes.py"

        # Read the routes.py file
        with open(file_path, "r") as file:
            content = file.read()

        # Find the current version using regex
        version_pattern = re.compile(r'version="(\d+\.\d+\.\d+)"')
        current_version = version_pattern.search(content).group(1)

        # Increment the patch version
        major, minor, patch = map(int, current_version.split('.'))
        new_version = f"{major}.{minor}.{patch + 1}"

        # Replace the old version with the new version
        new_content = version_pattern.sub(f'version="{new_version}"', content)

        # Write the new content back to routes.py
        with open(file_path, "w") as file:
            file.write(new_content)

        print(f"Updated version from {current_version} to {new_version}")
      shell: python
      
      
@tiadams what is your opinion on these, I can implement both of these easily if you also think they are OK.

**Comment by tiadams** [comment]
> For Angular versioning I found this: https://medium.com/@tolvaly.zs/how-to-version-number-angular-6-applications-4436c03a3bd3
> 
> For API versioning I found a code snippet like this:
> 
> ```
> - name: Increment API Version
>       id: increment_version
>       run: |
>         import re
> 
>         file_path = "backend/routes.py"
> 
>         # Read the routes.py file
>         with open(file_path, "r") as file:
>             content = file.read()
> 
>         # Find the current version using regex
>         version_pattern = re.compile(r'version="(\d+\.\d+\.\d+)"')
>         current_version = version_pattern.search(content).group(1)
> 
>         # Increment the patch version
>         major, minor, patch = map(int, current_version.split('.'))
>         new_version = f"{major}.{minor}.{patch + 1}"
> 
>         # Replace the old version with the new version
>         new_content = version_pattern.sub(f'version="{new_version}"', content)
> 
>         # Write the new content back to routes.py
>         with open(file_path, "w") as file:
>             file.write(new_content)
> 
>         print(f"Updated version from {current_version} to {new_version}")
>       shell: python
> ```
> 
> @tiadams what is your opinion on these, I can implement both of these easily if you also think they are OK.

This seems a bit overkill imo, we also already got the version from the current tag, should be solvable in one line by just editing the file, e.g. via sed. I did it here the other way around (getting the version from the API):
`
        echo "BACKEND_VERSION=$(echo "$(<backend/api/routes.py)" | grep -oP "(?<=version=\")[^\"]+")" >> "$GITHUB_OUTPUT"`

**Comment by mehmetcanay** [comment]
```bash
CURRENT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
VERSION=$(echo $CURRENT_TAG | grep -oP "(?<=v\.)[\d\.]+")
ROUTES_FILE="backend/api/routes.py"
PACKAGE_FILE="frontend/package-lock.json"
sed -i "s/version=\"[^\"]*\"/version=\"$VERSION\"/" $ROUTES_FILE
sed -i "s/version=\"[^\"]*\"/version=\"$VERSION\"/" $PACKAGE_FILE
```

Something like this?

**Comment by mehmetcanay** [comment]
> ```shell
> CURRENT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
> VERSION=$(echo $CURRENT_TAG | grep -oP "(?<=v\.)[\d\.]+")
> ROUTES_FILE="backend/api/routes.py"
> PACKAGE_FILE="frontend/package-lock.json"
> sed -i "s/version=\"[^\"]*\"/version=\"$VERSION\"/" $ROUTES_FILE
> sed -i "s/version=\"[^\"]*\"/version=\"$VERSION\"/" $PACKAGE_FILE
> ```
> 
> Something like this?

nvm this will not work for package-lock.json, I am looking for a solution.
