### ISSUE TITLE
Host DB Container in k8s

### ISSUE THREAD

**Issue by tiadams** [SCAI-BIO/PDataViewer#6]
- Decide on DB type
- Find Helm Chart & run in k8s
- Add data

**Comment by mehmetcanay** [comment]
@tiadams we have completed this right. Can I close the issue?

**Comment by mehmetcanay** [comment]
Instead of a dedicated SQL database, we utilized a file-based SQL database. Closing the issue for now, until we move on to a dedicated SQL database.
